name: Documentation

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r docs/doc-requirements.txt

      - name: Build docs
        run: |
          cd docs
          make html

      - name: publish to github pages
        if: github.ref == 'refs/heads/main'
        run: |
            pip install ghp-import
            ghp-import --no-jekyll --push --message "Update documentation [skip ci]" docs/_build/html